services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - POSTGRES_SERVER=db
      - REDIS_URL_DEV=redis://redis:6379/0
      - REDIS_URL_PROD=rediss://default:gQAAAAAAAe0_AAIgcDE1ZTFmNWUyMjE5MjE0Yjc1ODEwMGJkYWJjZmNlNWQ4Zg@sunny-dolphin-126271.upstash.io:6379
      - PYTHONUNBUFFERED=1
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - .:/app
