import React, { useEffect, useState } from 'react';
import axios from 'axios';

interface MeetingBriefTabProps {
  hcpId: string;
}

const MeetingBriefTab: React.FC<MeetingBriefTabProps> = ({ hcpId }) => {
  const [brief, setBrief] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const fetchBrief = async (refresh = false) => {
    try {
      setLoading(true);
      setError(null);
      const baseUrl = import.meta.env.VITE_API_URL || 'http://localhost:8000/api';
      const response = await axios.get(`${baseUrl}/hcp/${hcpId}/meeting-brief${refresh ? '?refresh=true' : ''}`);
      setBrief(response.data.data);
    } catch (err: any) {
      setError(err.message || 'Failed to load meeting brief');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchBrief();
  }, [hcpId]);

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center p-12 bg-white rounded-lg shadow-sm">
        <div className="animate-spin rounded-full h-10 w-10 border-b-2 border-blue-600 mb-4"></div>
        <p className="text-gray-500">The AI Planning System is preparing your meeting brief...</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="p-8 text-center bg-white rounded-lg shadow-sm border border-red-100">
        <p className="text-red-500 mb-4">{error}</p>
        <button onClick={() => fetchBrief(true)} className="px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700 transition-colors">Retry Generation</button>
      </div>
    );
  }

  if (!brief) return null;

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center bg-white p-5 rounded-lg shadow-sm border-l-4 border-blue-600">
        <div>
          <h2 className="text-xl font-bold text-gray-800">Today's Meeting Brief</h2>
          <p className="text-sm text-gray-500 mt-1">Generated by Curis AI Planning System</p>
        </div>
        <button 
          onClick={() => fetchBrief(true)}
          className="text-sm px-4 py-2 bg-gray-50 border border-gray-200 hover:bg-gray-100 text-gray-700 rounded-md transition-colors shadow-sm"
        >
          ↻ Refresh Brief
        </button>
      </div>

      <div className="bg-white p-6 rounded-lg shadow-sm border border-gray-100">
        <h3 className="text-lg font-semibold text-gray-800 mb-3 flex items-center">
          <svg className="w-5 h-5 mr-2 text-blue-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
          Executive Summary
        </h3>
        <p className="text-gray-700 leading-relaxed">{brief.summary}</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div className="bg-white p-6 rounded-lg shadow-sm border border-gray-100">
          <h3 className="text-lg font-semibold text-gray-800 mb-4 flex items-center">
            <svg className="w-5 h-5 mr-2 text-indigo-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2"></path></svg>
            Meeting Objectives
          </h3>
          <div className="mb-5">
            <span className="text-xs font-bold text-indigo-600 uppercase tracking-wider bg-indigo-50 px-2 py-1 rounded">Primary</span>
            <p className="text-gray-800 mt-2 font-medium">{brief.objectives?.primary_objective?.recommendation}</p>
            {brief.objectives?.primary_objective?.evidence && (
                <p className="text-xs text-gray-500 mt-1">Evidence: {brief.objectives.primary_objective.evidence}</p>
            )}
          </div>
          {brief.objectives?.secondary_objectives?.length > 0 && (
            <div>
              <span className="text-xs font-bold text-gray-500 uppercase tracking-wider">Secondary</span>
              <ul className="list-disc pl-5 mt-2 space-y-2">
                {brief.objectives.secondary_objectives.map((obj: any, idx: number) => (
                  <li key={idx} className="text-gray-700">{obj.recommendation}</li>
                ))}
              </ul>
            </div>
          )}
        </div>

        <div className="bg-white p-6 rounded-lg shadow-sm border border-gray-100">
          <h3 className="text-lg font-semibold text-gray-800 mb-4 flex items-center">
            <svg className="w-5 h-5 mr-2 text-emerald-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z"></path></svg>
            Conversation Strategy
          </h3>
          <div className="mb-5 bg-emerald-50 p-4 rounded-md border border-emerald-100">
            <span className="text-xs font-bold text-emerald-700 uppercase tracking-wider">Suggested Opening</span>
            <p className="text-emerald-900 mt-2 italic font-medium">"{brief.strategy?.suggested_opening?.recommendation}"</p>
          </div>
          {brief.strategy?.likely_questions?.length > 0 && (
            <div>
              <span className="text-xs font-bold text-gray-500 uppercase tracking-wider">Be Prepared For</span>
              <ul className="list-disc pl-5 mt-2 space-y-1">
                {brief.strategy.likely_questions.map((q: any, idx: number) => (
                  <li key={idx} className="text-gray-700">{q.recommendation}</li>
                ))}
              </ul>
            </div>
          )}
        </div>

        <div className="bg-white p-6 rounded-lg shadow-sm border border-gray-100">
          <h3 className="text-lg font-semibold text-gray-800 mb-4 flex items-center">
            <svg className="w-5 h-5 mr-2 text-rose-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"></path></svg>
            Risks & Commitments
          </h3>
          {brief.risks?.length > 0 && (
            <div className="mb-5">
              <span className="text-xs font-bold text-rose-600 uppercase tracking-wider bg-rose-50 px-2 py-1 rounded">Potential Risks</span>
              <ul className="list-disc pl-5 mt-3 space-y-2">
                {brief.risks.map((risk: any, idx: number) => (
                  <li key={idx} className="text-gray-700">{risk.recommendation}</li>
                ))}
              </ul>
            </div>
          )}
          {brief.commitments?.length > 0 && (
            <div>
              <span className="text-xs font-bold text-amber-600 uppercase tracking-wider bg-amber-50 px-2 py-1 rounded">Open Commitments</span>
              <ul className="list-disc pl-5 mt-3 space-y-2">
                {brief.commitments.map((c: any, idx: number) => (
                  <li key={idx} className="text-gray-700">{c.recommendation}</li>
                ))}
              </ul>
            </div>
          )}
          {(!brief.risks || brief.risks.length === 0) && (!brief.commitments || brief.commitments.length === 0) && (
              <p className="text-gray-500 italic">No significant risks or open commitments identified.</p>
          )}
        </div>

        <div className="bg-white p-6 rounded-lg shadow-sm border border-gray-100">
          <h3 className="text-lg font-semibold text-gray-800 mb-4 flex items-center">
            <svg className="w-5 h-5 mr-2 text-cyan-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253"></path></svg>
            Recommended Literature
          </h3>
          {brief.literature?.length > 0 ? (
            <ul className="list-disc pl-5 mt-1 space-y-3">
              {brief.literature.map((lit: any, idx: number) => (
                <li key={idx} className="text-gray-700">
                  <span className="font-medium block">{lit.recommendation}</span>
                  <span className="text-xs text-gray-500 block mt-1">{lit.evidence}</span>
                </li>
              ))}
            </ul>
          ) : (
            <p className="text-gray-500 italic mt-4 bg-gray-50 p-4 rounded text-center">No specific literature recommended for this meeting.</p>
          )}
        </div>
      </div>
    </div>
  );
};

export default MeetingBriefTab;
