"""Add key learnings to hcp memory

Revision ID: 0523f972fba4
Revises: 0e199858941c
Create Date: 2026-07-28 20:26:39.286127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0523f972fba4'
down_revision: Union[str, None] = '0e199858941c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hcp_memory', sa.Column('key_learnings', sa.JSON(), nullable=True))
    op.add_column('hcp_memory', sa.Column('behavioral_profile', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hcp_memory', 'behavioral_profile')
    op.drop_column('hcp_memory', 'key_learnings')
    # ### end Alembic commands ###
