"""Add key learnings and behavioral profile to HCPMemory

Revision ID: 0e199858941c
Revises: a0a01d7402c5
Create Date: 2026-07-28 20:06:22.484702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e199858941c'
down_revision: Union[str, None] = 'a0a01d7402c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
