"""Add Knowledge Engine models

Revision ID: 46ad278b6eda
Revises: 8b0ced2de85a
Create Date: 2026-07-28 11:20:41.176647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '46ad278b6eda'
down_revision: Union[str, None] = '8b0ced2de85a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_facts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hcp_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('COMMUNICATION', 'CLINICAL', 'COMMERCIAL', 'BEHAVIOR', 'RELATIONSHIP', 'PREFERENCE', name='factcategory'), nullable=False),
    sa.Column('attribute', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_interaction_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.Enum('INTERACTION', 'SYSTEM', 'USER', name='factsource'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', 'CONFLICTED', name='factstatus'), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_confirmed', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_snapshots',
    sa.Column('hcp_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('hcp_id', 'id')
    )
    op.create_index(op.f('ix_knowledge_snapshots_id'), 'knowledge_snapshots', ['id'], unique=False)
    op.create_table('knowledge_relations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hcp_id', sa.UUID(), nullable=False),
    sa.Column('from_fact', sa.UUID(), nullable=False),
    sa.Column('to_fact', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['from_fact'], ['knowledge_facts.id'], ),
    sa.ForeignKeyConstraint(['to_fact'], ['knowledge_facts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('knowledge_relations')
    op.drop_index(op.f('ix_knowledge_snapshots_id'), table_name='knowledge_snapshots')
    op.drop_table('knowledge_snapshots')
    op.drop_table('knowledge_facts')
    # ### end Alembic commands ###
