"""DDD refactoring models

Revision ID: 64d4bd24dfd7
Revises: 22ba47c4cd7c
Create Date: 2026-07-17 18:01:18.386247

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "64d4bd24dfd7"
down_revision: Union[str, None] = "22ba47c4cd7c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_messages",
        sa.Column("interaction_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["interaction_id"],
            ["interactions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chat_messages_id"), "chat_messages", ["id"], unique=False)
    op.drop_index(op.f("ix_interaction_products_id"), table_name="interaction_products")
    op.drop_table("interaction_products")

    op.drop_index(op.f("ix_interaction_attachments_id"), table_name="interaction_attachments")
    op.drop_table("interaction_attachments")
    op.drop_index(op.f("ix_follow_ups_id"), table_name="follow_ups")
    op.drop_table("follow_ups")
    op.drop_constraint(op.f("audit_logs_user_id_fkey"), "audit_logs", type_="foreignkey")
    op.drop_column("audit_logs", "user_id")
    op.add_column("hcps", sa.Column("name", sa.String(length=255), nullable=False))
    op.add_column("hcps", sa.Column("specialization", sa.String(length=255), nullable=True))
    op.add_column("hcps", sa.Column("hospital_name", sa.String(length=255), nullable=True))
    op.add_column("hcps", sa.Column("city", sa.String(length=255), nullable=True))
    op.add_column("hcps", sa.Column("notes", sa.Text(), nullable=True))
    op.drop_constraint(op.f("hcps_email_key"), "hcps", type_="unique")
    op.drop_column("hcps", "last_name")
    op.drop_column("hcps", "email")
    op.drop_column("hcps", "hospital_affiliation")
    op.drop_column("hcps", "specialty")
    op.drop_column("hcps", "first_name")
    op.drop_column("hcps", "metadata_")
    op.drop_column("hcps", "phone")
    op.add_column(
        "interactions", sa.Column("interaction_type", sa.String(length=100), nullable=True)
    )
    op.add_column("interactions", sa.Column("date", sa.Date(), nullable=True))
    op.add_column("interactions", sa.Column("time", sa.Time(), nullable=True))
    op.add_column("interactions", sa.Column("attendees", sa.Text(), nullable=True))
    op.add_column("interactions", sa.Column("topics_discussed", sa.Text(), nullable=True))
    op.add_column("interactions", sa.Column("materials_shared", sa.Text(), nullable=True))
    op.add_column("interactions", sa.Column("samples_distributed", sa.Text(), nullable=True))
    op.add_column("interactions", sa.Column("sentiment", sa.String(length=50), nullable=True))
    op.add_column("interactions", sa.Column("outcomes", sa.Text(), nullable=True))
    op.add_column("interactions", sa.Column("follow_up_actions", sa.Text(), nullable=True))
    op.add_column(
        "interactions", sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.alter_column("interactions", "hcp_id", existing_type=sa.UUID(), nullable=True)
    op.drop_constraint(op.f("interactions_user_id_fkey"), "interactions", type_="foreignkey")
    op.drop_column("interactions", "type")
    op.drop_column("interactions", "interaction_date")
    op.drop_column("interactions", "user_id")
    op.drop_column("interactions", "notes")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("interactions", sa.Column("notes", sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column(
        "interactions", sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "interactions",
        sa.Column(
            "interaction_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "interactions",
        sa.Column("type", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        op.f("interactions_user_id_fkey"), "interactions", "users", ["user_id"], ["id"]
    )
    op.alter_column("interactions", "hcp_id", existing_type=sa.UUID(), nullable=False)
    op.drop_column("interactions", "completed_at")
    op.drop_column("interactions", "follow_up_actions")
    op.drop_column("interactions", "outcomes")
    op.drop_column("interactions", "sentiment")
    op.drop_column("interactions", "samples_distributed")
    op.drop_column("interactions", "materials_shared")
    op.drop_column("interactions", "topics_discussed")
    op.drop_column("interactions", "attendees")
    op.drop_column("interactions", "time")
    op.drop_column("interactions", "date")
    op.drop_column("interactions", "interaction_type")
    op.add_column(
        "hcps", sa.Column("phone", sa.VARCHAR(length=50), autoincrement=False, nullable=True)
    )
    op.add_column(
        "hcps",
        sa.Column(
            "metadata_", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "hcps", sa.Column("first_name", sa.VARCHAR(length=100), autoincrement=False, nullable=False)
    )
    op.add_column(
        "hcps", sa.Column("specialty", sa.VARCHAR(length=100), autoincrement=False, nullable=False)
    )
    op.add_column(
        "hcps",
        sa.Column(
            "hospital_affiliation", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "hcps", sa.Column("email", sa.VARCHAR(length=255), autoincrement=False, nullable=True)
    )
    op.add_column(
        "hcps", sa.Column("last_name", sa.VARCHAR(length=100), autoincrement=False, nullable=False)
    )
    op.create_unique_constraint(
        op.f("hcps_email_key"), "hcps", ["email"], postgresql_nulls_not_distinct=False
    )
    op.drop_column("hcps", "notes")
    op.drop_column("hcps", "city")
    op.drop_column("hcps", "hospital_name")
    op.drop_column("hcps", "specialization")
    op.drop_column("hcps", "name")
    op.add_column("audit_logs", sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(
        op.f("audit_logs_user_id_fkey"), "audit_logs", "users", ["user_id"], ["id"]
    )
    op.create_table(
        "follow_ups",
        sa.Column("interaction_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "due_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column("action_item", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("is_completed", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["interaction_id"], ["interactions.id"], name=op.f("follow_ups_interaction_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("follow_ups_pkey")),
    )
    op.create_index(op.f("ix_follow_ups_id"), "follow_ups", ["id"], unique=False)
    op.create_table(
        "interaction_attachments",
        sa.Column("interaction_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("file_name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("file_url", sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["interaction_id"],
            ["interactions.id"],
            name=op.f("interaction_attachments_interaction_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("interaction_attachments_pkey")),
    )
    op.create_index(
        op.f("ix_interaction_attachments_id"), "interaction_attachments", ["id"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("email", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("hashed_password", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("first_name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("last_name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("role", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("users_pkey")),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "interaction_products",
        sa.Column("interaction_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("product_name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("reaction", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["interaction_id"],
            ["interactions.id"],
            name=op.f("interaction_products_interaction_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("interaction_products_pkey")),
    )
    op.create_index(
        op.f("ix_interaction_products_id"), "interaction_products", ["id"], unique=False
    )
    op.drop_index(op.f("ix_chat_messages_id"), table_name="chat_messages")
    op.drop_table("chat_messages")
    # ### end Alembic commands ###
