"""Add HCP Memory

Revision ID: 8b0ced2de85a
Revises: e5dadc1e8481
Create Date: 2026-07-26 18:01:40.848084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b0ced2de85a'
down_revision: Union[str, None] = 'e5dadc1e8481'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hcp_memory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hcp_id', sa.UUID(), nullable=False),
    sa.Column('communication_style', sa.String(), nullable=True),
    sa.Column('clinical_interests', sa.JSON(), nullable=True),
    sa.Column('preferred_products', sa.JSON(), nullable=True),
    sa.Column('common_objections', sa.JSON(), nullable=True),
    sa.Column('preferred_meeting_time', sa.String(), nullable=True),
    sa.Column('favorite_materials', sa.JSON(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['hcp_id'], ['hcps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hcp_id')
    )
    op.create_index(op.f('ix_hcp_memory_id'), 'hcp_memory', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hcp_memory_id'), table_name='hcp_memory')
    op.drop_table('hcp_memory')
    # ### end Alembic commands ###
