"""Add Meeting Brief Cache model

Revision ID: 8b5668217b92
Revises: d784fbf560b4
Create Date: 2026-07-28 11:31:58.194764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b5668217b92'
down_revision: Union[str, None] = 'd784fbf560b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_brief_cache',
    sa.Column('hcp_id', sa.UUID(), nullable=False),
    sa.Column('digital_twin_version', sa.String(), nullable=False),
    sa.Column('brief_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('hcp_id', 'id')
    )
    op.create_index(op.f('ix_meeting_brief_cache_id'), 'meeting_brief_cache', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meeting_brief_cache_id'), table_name='meeting_brief_cache')
    op.drop_table('meeting_brief_cache')
    # ### end Alembic commands ###
