"""Add Digital Twin Cache model

Revision ID: d784fbf560b4
Revises: 46ad278b6eda
Create Date: 2026-07-28 11:29:09.733270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd784fbf560b4'
down_revision: Union[str, None] = '46ad278b6eda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('digital_twin_cache',
    sa.Column('hcp_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('twin_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('hcp_id', 'id')
    )
    op.create_index(op.f('ix_digital_twin_cache_id'), 'digital_twin_cache', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_digital_twin_cache_id'), table_name='digital_twin_cache')
    op.drop_table('digital_twin_cache')
    # ### end Alembic commands ###
