"""add status and completed_at to interaction

Revision ID: e7c0809aa321
Revises: 64d4bd24dfd7
Create Date: 2026-07-18 02:20:46.686026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7c0809aa321'
down_revision: Union[str, None] = '64d4bd24dfd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
